import { College, Department, PyqDocument, RoomListing, RoommateProfile, SeniorProfile, Internship } from './types';

export const MOCK_COLLEGES: College[] = [
  { id: 'c1', name: 'National Institute of Technology (NITD)', city: 'Delhi', state: 'Delhi', status: 'verified' },
  { id: 'c2', name: 'Delhi University (DU)', city: 'Delhi', state: 'Delhi', status: 'verified' },
  { id: 'c3', name: 'Birla Institute of Technology (BITS)', city: 'Pilani', state: 'Rajasthan', status: 'verified' },
  { id: 'c4', name: 'Delhi Technological University (DTU)', city: 'Delhi', state: 'Delhi', status: 'verified' },
  { id: 'c5', name: 'Netaji Subhas University of Technology (NSUT)', city: 'Delhi', state: 'Delhi', status: 'verified' },
  { id: 'c6', name: 'Indian Institute of Technology (IIT Delhi)', city: 'Delhi', state: 'Delhi', status: 'verified' },
  { id: 'c7', name: 'Guru Gobind Singh Indraprastha University (GGSIPU)', city: 'Delhi', state: 'Delhi', status: 'verified' },
  { id: 'c8', name: 'Lovely Professional University (LPU)', city: 'Phagwara', state: 'Punjab', status: 'verified' },
  { id: 'c9', name: 'Galgotias University', city: 'Greater Noida', state: 'Uttar Pradesh', status: 'verified' },
  { id: 'c10', name: 'Babu Banarasi Das University (BBD)', city: 'Lucknow', state: 'Uttar Pradesh', status: 'verified' },
  { id: 'c11', name: 'LNCT Group of Colleges', city: 'Bhopal', state: 'Madhya Pradesh', status: 'verified' },
  { id: 'c12', name: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)', city: 'Bhopal', state: 'Madhya Pradesh', status: 'verified' },
  { id: 'c13', name: 'Technocrats Institute of Technology (TIT)', city: 'Bhopal', state: 'Madhya Pradesh', status: 'verified' },
  { id: 'c14', name: 'Oriental University', city: 'Indore', state: 'Madhya Pradesh', status: 'verified' },
  { id: 'c15', name: 'Devi Ahilya Vishwavidyalaya (DAVV)', city: 'Indore', state: 'Madhya Pradesh', status: 'verified' },
  { id: 'c16', name: 'Amity University', city: 'Noida', state: 'Uttar Pradesh', status: 'verified' },
  { id: 'c17', name: 'Sharda University', city: 'Greater Noida', state: 'Uttar Pradesh', status: 'verified' },
  { id: 'c18', name: 'SRM Institute of Science and Technology', city: 'Chennai', state: 'Tamil Nadu', status: 'verified' },
  { id: 'c19', name: 'Vellore Institute of Technology (VIT)', city: 'Vellore', state: 'Tamil Nadu', status: 'verified' },
  { id: 'c20', name: 'Manipal Academy of Higher Education', city: 'Manipal', state: 'Karnataka', status: 'verified' },
  { id: 'c21', name: 'Thapar Institute of Engineering & Technology', city: 'Patiala', state: 'Punjab', status: 'verified' },
  { id: 'c22', name: 'KIIT University', city: 'Bhubaneswar', state: 'Odisha', status: 'verified' },
  { id: 'c23', name: 'Chandigarh University (CU)', city: 'Mohali', state: 'Punjab', status: 'verified' },
  { id: 'c24', name: 'NMIMS University', city: 'Mumbai', state: 'Maharashtra', status: 'verified' },
  { id: 'c25', name: 'Symbiosis International University', city: 'Pune', state: 'Maharashtra', status: 'verified' }
];

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'cs1', collegeId: 'c1', name: 'B.Tech Computer Science' },
  { id: 'bca1', collegeId: 'c1', name: 'BCA' },
  { id: 'bcom1', collegeId: 'c2', name: 'B.Com (Hons)' },
  { id: 'ba_english', collegeId: 'c2', name: 'B.A. English (Hons)' },
  { id: 'cs2', collegeId: 'c3', name: 'B.Tech Computer Science' },
  { id: 'cs_dtu', collegeId: 'c4', name: 'B.Tech Computer Science (CSE)' },
  { id: 'ece_nsut', collegeId: 'c5', name: 'B.Tech Electronics & Communication' },
  { id: 'cs_iitd', collegeId: 'c6', name: 'B.Tech Computer Science' },
  { id: 'bca_ggsipu', collegeId: 'c7', name: 'BCA (Computer Applications)' },
  { id: 'cs_lpu', collegeId: 'c8', name: 'B.Tech Computer Science & Eng' },
  { id: 'cs_galgotia', collegeId: 'c9', name: 'B.Tech Computer Science' },
  { id: 'cs_bbd', collegeId: 'c10', name: 'B.Tech Computer Science' },
  { id: 'cs_lnct', collegeId: 'c11', name: 'B.Tech Computer Science' },
  { id: 'cs_rgpv', collegeId: 'c12', name: 'B.Tech Computer Science' },
  { id: 'cs_tit', collegeId: 'c13', name: 'B.Tech Computer Science' },
  { id: 'cs_oriental', collegeId: 'c14', name: 'B.Tech Computer Science' },
  { id: 'cs_davv', collegeId: 'c15', name: 'B.Tech Computer Science' },
  { id: 'cs_amity', collegeId: 'c16', name: 'B.Tech Computer Science' },
  { id: 'cs_sharda', collegeId: 'c17', name: 'B.Tech Computer Science' },
  { id: 'cs_srm', collegeId: 'c18', name: 'B.Tech Computer Science' },
  { id: 'cs_vit', collegeId: 'c19', name: 'B.Tech Computer Science' },
  { id: 'cs_manipal', collegeId: 'c20', name: 'B.Tech Computer Science' },
  { id: 'cs_thapar', collegeId: 'c21', name: 'B.Tech Computer Science' },
  { id: 'cs_kiit', collegeId: 'c22', name: 'B.Tech Computer Science' },
  { id: 'cs_chandigarh', collegeId: 'c23', name: 'B.Tech Computer Science' },
  { id: 'cs_nmims', collegeId: 'c24', name: 'B.Tech Computer Science' },
  { id: 'cs_symbiosis', collegeId: 'c25', name: 'B.Tech Computer Science' }
];

export const MOCK_PYQS: PyqDocument[] = [
  {
    id: 'd1',
    title: 'Operating Systems - 2023 Final Paper',
    subject: 'Operating Systems',
    type: 'pyq',
    year: 2023,
    authorName: 'Rahul K.',
    downloadCount: 1240,
    rating: 4.8,
    tags: ['OS', 'Finals', '2023'],
    collegeId: 'c1',
    departmentId: 'cs1',
    downloadUrl: 'https://nitdelhi.ac.in/?page_id=12558'
  },
  {
    id: 'd2',
    title: 'Data Structures Handwritten Notes',
    subject: 'Data Structures',
    type: 'notes',
    authorName: 'Priya S.',
    downloadCount: 3400,
    rating: 4.9,
    tags: ['DSA', 'Notes', 'Mid-terms'],
    collegeId: 'c1',
    departmentId: 'cs1',
    downloadUrl: 'https://nitdelhi.ac.in/?page_id=12558'
  },
  {
    id: 'd3',
    title: 'Database Management Systems Syllabus & Blueprint',
    subject: 'DBMS',
    type: 'syllabus',
    year: 2024,
    authorName: 'Admin',
    downloadCount: 560,
    rating: 5.0,
    tags: ['DBMS', 'Syllabus'],
    collegeId: 'c2',
    departmentId: 'bcom1',
    downloadUrl: 'https://www.tutorialsduniya.com/du-previous-year-question-papers/'
  },
  {
    id: 'd4',
    title: 'Delhi University B.A. English Honors Complete Syllabus',
    subject: 'English Literature',
    type: 'syllabus',
    year: 2023,
    authorName: 'DU Academic Council',
    downloadCount: 1890,
    rating: 4.7,
    tags: ['English', 'Literature', 'Syllabus'],
    collegeId: 'c2',
    departmentId: 'ba_english',
    downloadUrl: 'https://www.du.ac.in/index.php?page=revised-syllabi-under-ugcf-2022'
  },
  {
    id: 'd5',
    title: 'DTU B.Tech First Year Maths-1 Core Past Papers',
    subject: 'Applied Mathematics',
    type: 'pyq',
    year: 2022,
    authorName: 'Siddharth M.',
    downloadCount: 4120,
    rating: 4.9,
    tags: ['Maths-1', 'First Year', 'Past Papers'],
    collegeId: 'c4',
    departmentId: 'cs_dtu',
    downloadUrl: 'https://www.studentsuvidha.com/forum/delhi-technological-university-dtu/'
  },
  {
    id: 'd6',
    title: 'DTU CSE Scheme, Course Credits & Syllabus Guide',
    subject: 'Computer Science',
    type: 'syllabus',
    year: 2024,
    authorName: 'DTU Exam Board',
    downloadCount: 2280,
    rating: 4.8,
    tags: ['CSE', 'Syllabus', 'DTU Core'],
    collegeId: 'c4',
    departmentId: 'cs_dtu',
    downloadUrl: 'http://dtu.ac.in/Web/Academics/syllabus.php'
  },
  {
    id: 'd7',
    title: 'NSUT Electronics B.Tech Engineering Core Syllabus & Scheme',
    subject: 'Electronics & Communication',
    type: 'syllabus',
    year: 2023,
    authorName: 'NSUT Academics',
    downloadCount: 1640,
    rating: 4.6,
    tags: ['ECE', 'Syllabus', 'NSUT Core'],
    collegeId: 'c5',
    departmentId: 'ece_nsut',
    downloadUrl: 'http://www.nsut.ac.in/en/academics/curriculum'
  },
  {
    id: 'd8',
    title: 'NSUT Basic Electrical Engineering Notes & Solved PYQs',
    subject: 'Electrical Engineering',
    type: 'notes',
    year: 2023,
    authorName: 'Kartik S.',
    downloadCount: 2950,
    rating: 4.9,
    tags: ['EE', 'First Year Notes', 'NSUT'],
    collegeId: 'c5',
    departmentId: 'ece_nsut',
    downloadUrl: 'https://www.studentsuvidha.com/forum/netaji-subhas-university-of-technology-nsut-formerly-nsit/'
  },
  {
    id: 'd9',
    title: 'IIT Delhi B.Tech Computer Science Course Structure Guide',
    subject: 'Computer Science',
    type: 'syllabus',
    year: 2024,
    authorName: 'IITD Academic Senate',
    downloadCount: 5100,
    rating: 5.0,
    tags: ['IIT Delhi', 'CSE', 'Curriculum'],
    collegeId: 'c6',
    departmentId: 'cs_iitd',
    downloadUrl: 'https://home.iitd.ac.in/curriculum.php'
  },
  {
    id: 'd10',
    title: 'GGSIPU IP University BCA Computer Applications Syllabus Guide',
    subject: 'BCA Applications',
    type: 'syllabus',
    year: 2023,
    authorName: 'IPU Registrar',
    downloadCount: 3820,
    rating: 4.7,
    tags: ['IPU', 'BCA', 'Syllabus'],
    collegeId: 'c7',
    departmentId: 'bca_ggsipu',
    downloadUrl: 'https://www.tutorialsduniya.com/ipu-previous-year-question-papers/'
  },
  {
    id: 'd11',
    title: 'GGSIPU BBA Administration Syllabus & Past Exams Paper blueprint',
    subject: 'Business Administration',
    type: 'syllabus',
    year: 2023,
    authorName: 'IPU Business School',
    downloadCount: 2460,
    rating: 4.8,
    tags: ['BBA', 'IPU', 'Past Scheme'],
    collegeId: 'c7',
    departmentId: 'bca_ggsipu',
    downloadUrl: 'https://www.tutorialsduniya.com/ipu-previous-year-question-papers/'
  },
  {
    id: 'd12',
    title: 'LPU Computer Science & Engineering Complete Syllabus Scheme',
    subject: 'CSE Engineering',
    type: 'syllabus',
    year: 2024,
    authorName: 'LPU Dean Office',
    downloadCount: 3150,
    rating: 4.8,
    tags: ['LPU', 'CSE', 'Curriculum'],
    collegeId: 'c8',
    departmentId: 'cs_lpu',
    downloadUrl: 'https://www.lpu.in/programmes/all/12th/engineering/b-tech/computer-science'
  },
  {
    id: 'd13',
    title: 'Galgotias University B.Tech CSE Final Sem Exam Pattern Blueprint',
    subject: 'Computer Science',
    type: 'pyq',
    year: 2023,
    authorName: 'Prof. J. Roy',
    downloadCount: 1980,
    rating: 4.7,
    tags: ['Galgotias', 'CSE', 'Blueprints'],
    collegeId: 'c9',
    departmentId: 'cs_galgotia',
    downloadUrl: 'https://www.galgotiasuniversity.edu.in/p/programs/under-graduate/btech-computer-science-engineering'
  },
  {
    id: 'd14',
    title: 'BBD University B.Tech Engineering Rules & Syllabus Guide',
    subject: 'BBD Scheme',
    type: 'syllabus',
    year: 2023,
    authorName: 'BBD University',
    downloadCount: 890,
    rating: 4.6,
    tags: ['BBD', 'Syllabus', 'Lucknow'],
    collegeId: 'c10',
    departmentId: 'cs_bbd',
    downloadUrl: 'https://bbdu.ac.in/school-of-engineering/'
  },
  {
    id: 'd15',
    title: 'LNCT Group of Colleges B.Tech CSE Syllabus & Scheme (RGPV Affiliated)',
    subject: 'CSE Core',
    type: 'syllabus',
    year: 2024,
    authorName: 'LNCT Academic Cell',
    downloadCount: 1420,
    rating: 4.8,
    tags: ['LNCT', 'RGPV Online', 'Syllabus', 'Bhopal'],
    collegeId: 'c11',
    departmentId: 'cs_lnct',
    downloadUrl: 'https://www.rgpvonline.com/btech-notes.html'
  },
  {
    id: 'd15_2',
    title: 'LNCT Group of Colleges - RGPV B.Tech 1st Year Question Papers & Solved Guide',
    subject: 'Engineering Physics & Maths',
    type: 'pyq',
    year: 2023,
    authorName: 'LNCT Exam Cell / RGPV Online',
    downloadCount: 3210,
    rating: 4.9,
    tags: ['LNCT', 'RGPV Online', 'First Year PYQ'],
    collegeId: 'c11',
    departmentId: 'cs_lnct',
    downloadUrl: 'https://www.rgpvonline.com/rgpv-first-year-question-papers.html'
  },
  {
    id: 'd15_3',
    title: 'LNCT Group of Colleges - RGPV 3rd & 4th Sem CSE Previous Year Question Papers',
    subject: 'Computer Science',
    type: 'pyq',
    year: 2023,
    authorName: 'LNCT Student Forum / RGPV Online',
    downloadCount: 2890,
    rating: 4.8,
    tags: ['LNCT', 'RGPV Online', 'CSE PYQ'],
    collegeId: 'c11',
    departmentId: 'cs_lnct',
    downloadUrl: 'https://www.rgpvonline.com/btech-cse-question-papers.html'
  },
  {
    id: 'd15_4',
    title: 'LNCT Group of Colleges - RGPV Mid-Sem Exam Model Papers & Lecture Notes',
    subject: 'DSA & Operating Systems',
    type: 'notes',
    year: 2024,
    authorName: 'LNCT Faculty Notes',
    downloadCount: 1950,
    rating: 4.7,
    tags: ['LNCT', 'RGPV Online', 'Lecture Notes'],
    collegeId: 'c11',
    departmentId: 'cs_lnct',
    downloadUrl: 'https://www.rgpvonline.com/btech-notes.html'
  },
  {
    id: 'd16',
    title: 'RGPV Bhopal B.Tech First Year Common Engineering Papers Guide',
    subject: 'Engineering Physics & Maths',
    type: 'pyq',
    year: 2023,
    authorName: 'RGPV Exam Cell',
    downloadCount: 4680,
    rating: 4.9,
    tags: ['RGPV', 'Bhopal', 'First Year PYQ'],
    collegeId: 'c12',
    departmentId: 'cs_rgpv',
    downloadUrl: 'https://www.rgpvonline.com/rgpv-first-year-question-papers.html'
  },
  {
    id: 'd17',
    title: 'TIT Bhopal Technocrats B.Tech CSE Subject Scheme (Affiliated to RGPV)',
    subject: 'Computer Science',
    type: 'syllabus',
    year: 2024,
    authorName: 'TIT Dean Office',
    downloadCount: 1150,
    rating: 4.7,
    tags: ['TIT', 'Bhopal', 'CSE Core'],
    collegeId: 'c13',
    departmentId: 'cs_tit',
    downloadUrl: 'https://www.rgpvonline.com/btech-cse-question-papers.html'
  },
  {
    id: 'd17_2',
    title: 'TIT Bhopal Technocrats - RGPV First Year Common Engineering Solved PYQs',
    subject: 'Engineering Chemistry & Maths',
    type: 'pyq',
    year: 2023,
    authorName: 'TIT Exam Cell',
    downloadCount: 1620,
    rating: 4.8,
    tags: ['TIT', 'RGPV Online', 'PYQ'],
    collegeId: 'c13',
    departmentId: 'cs_tit',
    downloadUrl: 'https://www.rgpvonline.com/rgpv-first-year-question-papers.html'
  },
  {
    id: 'd18',
    title: 'Oriental University Indore B.Tech Subject Syllabus Guide (RGPV Affiliation)',
    subject: 'Core Engineering',
    type: 'syllabus',
    year: 2024,
    authorName: 'Oriental Univ',
    downloadCount: 920,
    rating: 4.6,
    tags: ['Oriental', 'Indore', 'Syllabus'],
    collegeId: 'c14',
    departmentId: 'cs_oriental',
    downloadUrl: 'https://www.rgpvonline.com/rgpv-syllabus.html'
  },
  {
    id: 'd19',
    title: 'DAVV Indore Devi Ahilya Vishwavidyalaya CSE Core Syllabus',
    subject: 'Computer Engineering',
    type: 'syllabus',
    year: 2024,
    authorName: 'DAVV Board of Studies',
    downloadCount: 3840,
    rating: 4.9,
    tags: ['DAVV', 'Indore', 'Syllabus'],
    collegeId: 'c15',
    departmentId: 'cs_davv',
    downloadUrl: 'https://www.davvonline.com/davv-engineering-question-papers.html'
  },
  {
    id: 'd20',
    title: 'Amity University Noida Engineering Prospectus & Complete Syllabus',
    subject: 'Computer Science',
    type: 'syllabus',
    year: 2024,
    authorName: 'Amity Noida',
    downloadCount: 2240,
    rating: 4.8,
    tags: ['Amity', 'Noida', 'Syllabus'],
    collegeId: 'c16',
    departmentId: 'cs_amity',
    downloadUrl: 'https://www.amity.edu/aaset/curriculum-btech-cse.asp'
  },
  {
    id: 'd21',
    title: 'Sharda University Greater Noida Engineering Course Curriculum',
    subject: 'Core CS',
    type: 'syllabus',
    year: 2024,
    authorName: 'Sharda Board',
    downloadCount: 1350,
    rating: 4.7,
    tags: ['Sharda', 'Noida', 'Syllabus'],
    collegeId: 'c17',
    departmentId: 'cs_sharda',
    downloadUrl: 'https://www.sharda.ac.in/programmes/btech-computer-science'
  },
  {
    id: 'd22',
    title: 'SRM Chennai B.Tech Core Computer Science Syllabus & Guide',
    subject: 'CSE Core',
    type: 'syllabus',
    year: 2024,
    authorName: 'SRM Academics',
    downloadCount: 2790,
    rating: 4.8,
    tags: ['SRM', 'Chennai', 'Syllabus'],
    collegeId: 'c18',
    departmentId: 'cs_srm',
    downloadUrl: 'https://www.srmist.edu.in/department/department-of-computer-science-engineering/'
  },
  {
    id: 'd23',
    title: 'VIT Vellore B.Tech Computer Science Core Engineering Guide',
    subject: 'CSE Core',
    type: 'syllabus',
    year: 2024,
    authorName: 'VIT Registrar',
    downloadCount: 4320,
    rating: 4.9,
    tags: ['VIT', 'Vellore', 'Syllabus'],
    collegeId: 'c19',
    departmentId: 'cs_vit',
    downloadUrl: 'https://vit.ac.in/school/site/programmes/undergraduate/btech-cse'
  },
  {
    id: 'd24',
    title: 'Manipal B.Tech Computer Science Program Structure & Course Syllabus',
    subject: 'Syllabus',
    type: 'syllabus',
    year: 2024,
    authorName: 'MAHE Dean',
    downloadCount: 1980,
    rating: 4.8,
    tags: ['Manipal', 'CSE', 'Syllabus'],
    collegeId: 'c20',
    departmentId: 'cs_manipal',
    downloadUrl: 'https://manipal.edu/mit/program-list/btech/btech-computer-science-and-engineering.html'
  },
  {
    id: 'd25',
    title: 'Thapar Institute Patiala B.Tech Core Curriculum Syllabus Guide',
    subject: 'Core Engineering',
    type: 'syllabus',
    year: 2024,
    authorName: 'TIET Board',
    downloadCount: 1560,
    rating: 4.7,
    tags: ['Thapar', 'Patiala', 'Syllabus'],
    collegeId: 'c21',
    departmentId: 'cs_thapar',
    downloadUrl: 'https://cl.thapar.edu/exampapers.php'
  }
];

export const MOCK_ROOMS: RoomListing[] = [
  {
    id: 'r1',
    title: 'Spacious Single Room near DU North Campus',
    type: 'single',
    rent: 8500,
    city: 'Delhi',
    distanceFromCampus: 1.2,
    amenities: ['WiFi', 'AC', 'Attached Bath'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Amit Verma',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c2',
    redirectUrl: 'https://www.housing.com/rent/pg-in-delhi'
  },
  {
    id: 'r2',
    title: 'Twin Sharing PG with Food near NITD',
    type: 'pg',
    rent: 12000,
    city: 'Delhi',
    distanceFromCampus: 0.5,
    amenities: ['WiFi', 'Food', 'Laundry', 'AC'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'Sharma PG Hub',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c1',
    redirectUrl: 'https://www.nobroker.in/property/rent/delhi/'
  },
  {
    id: 'r3',
    title: 'Premium Flat-Share near BITS Pilani Campus',
    type: 'sharing',
    rent: 6000,
    city: 'Pilani',
    distanceFromCampus: 2.0,
    amenities: ['WiFi', 'Library', 'Mess'],
    genderPreference: 'female',
    status: 'available',
    verified: true,
    ownerName: 'Campus Living Pilani',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c3',
    redirectUrl: 'https://www.stanzaliving.com/'
  },
  {
    id: 'r4',
    title: 'DTU Rohini Student House & AC PG',
    type: 'pg',
    rent: 9500,
    city: 'Delhi',
    distanceFromCampus: 0.8,
    amenities: ['WiFi', 'AC', 'Mess Food', 'Study Desk'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'Rohini Student Care',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c4',
    redirectUrl: 'https://www.magicbricks.com/pg-in-delhi-pppfr'
  },
  {
    id: 'r5',
    title: 'NSUT Dwarka Sector 3 Girls & Boys PG',
    type: 'pg',
    rent: 11000,
    city: 'Delhi',
    distanceFromCampus: 0.6,
    amenities: ['WiFi', 'AC', '3 Meals Included', 'Gym'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Dwarka Residency',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c5',
    redirectUrl: 'https://www.nobroker.in/property/rent/delhi/'
  },
  {
    id: 'r6',
    title: 'IIT Delhi Hauz Khas Luxury Student Flat',
    type: 'single',
    rent: 14000,
    city: 'Delhi',
    distanceFromCampus: 0.4,
    amenities: ['High Speed WiFi', 'AC', 'Housekeeping', 'Power Backup'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Hauz Khas Stays',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c6',
    redirectUrl: 'https://www.stanzaliving.com/delhi'
  },
  {
    id: 'r7',
    title: 'GGSIPU Dwarka Campus Deluxe Hostel',
    type: 'hostel',
    rent: 8000,
    city: 'Delhi',
    distanceFromCampus: 1.0,
    amenities: ['WiFi', 'AC', 'Canteen', 'Security'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'IP Student Hostel',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c7',
    redirectUrl: 'https://www.magicbricks.com/pg-in-delhi-pppfr'
  },
  {
    id: 'r8',
    title: 'Single Room for LPU Students',
    type: 'single',
    rent: 5500,
    city: 'Phagwara',
    distanceFromCampus: 1.5,
    amenities: ['WiFi', 'Gym', 'Laundry'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Singh Residency',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c8',
    redirectUrl: 'https://www.amberstudent.com/'
  },
  {
    id: 'r9',
    title: 'Galgotias Student PG near Knowledge Park',
    type: 'pg',
    rent: 7500,
    city: 'Greater Noida',
    distanceFromCampus: 1.0,
    amenities: ['WiFi', 'AC', 'Power Backup', 'Mess'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'Noida Green PG',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c9',
    redirectUrl: 'https://www.stanzaliving.com/greater-noida'
  },
  {
    id: 'r10',
    title: 'Affordable Single Room near BBD University',
    type: 'single',
    rent: 5000,
    city: 'Lucknow',
    distanceFromCampus: 1.7,
    amenities: ['WiFi', 'Water Cooler', 'Bed'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'Awadh PG Rentals',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c10',
    redirectUrl: 'https://www.magicbricks.com/pg-in-lucknow-pppfr'
  },
  {
    id: 'r11',
    title: 'Spacious Flat-Share near LNCT Group of Colleges & RGPV',
    type: 'sharing',
    rent: 4500,
    city: 'Bhopal',
    distanceFromCampus: 1.2,
    amenities: ['WiFi', 'Kitchen', 'RO Water', 'Mess Facility'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'LNCT Student Living',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c11',
    redirectUrl: 'https://www.housing.com/rent/pg-in-bhopal'
  },
  {
    id: 'r11_2',
    title: 'LNCT Anand Nagar Executive Boys & Girls PG',
    type: 'pg',
    rent: 5500,
    city: 'Bhopal',
    distanceFromCampus: 0.6,
    amenities: ['High Speed WiFi', '3 Meals Included', 'AC', 'Study Desk'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Anand Nagar Student Care',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c11',
    redirectUrl: 'https://www.magicbricks.com/pg-in-bhopal-pppfr'
  },
  {
    id: 'r11_3',
    title: 'Indrapuri Sector C Student Flats near LNCT & RGPV',
    type: 'sharing',
    rent: 4800,
    city: 'Bhopal',
    distanceFromCampus: 1.5,
    amenities: ['WiFi', 'Kitchen', 'Power Backup', 'Geyser'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'Indrapuri PG Hub',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c11',
    redirectUrl: 'https://www.nobroker.in/'
  },
  {
    id: 'r11_4',
    title: 'Ayodhya Bypass AC Hostel with Food',
    type: 'hostel',
    rent: 6200,
    city: 'Bhopal',
    distanceFromCampus: 1.0,
    amenities: ['WiFi', 'AC', 'Canteen', 'Security'],
    genderPreference: 'female',
    status: 'available',
    verified: true,
    ownerName: 'Bhopal Girls Residency',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c11',
    redirectUrl: 'https://www.stanzaliving.com/'
  },
  {
    id: 'r12',
    title: 'RGPV Campus View Student PG Bhopal',
    type: 'pg',
    rent: 5000,
    city: 'Bhopal',
    distanceFromCampus: 0.9,
    amenities: ['WiFi', 'Food', 'AC', 'Security'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'RGPV PG Network',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c12',
    redirectUrl: 'https://www.nobroker.in/'
  },
  {
    id: 'r13',
    title: 'Premium Girls PG near TIT Campus Bhopal',
    type: 'pg',
    rent: 6500,
    city: 'Bhopal',
    distanceFromCampus: 0.8,
    amenities: ['WiFi', 'AC', 'Attached Bath', 'Security'],
    genderPreference: 'female',
    status: 'available',
    verified: true,
    ownerName: 'Shrishti Girls Hostel',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c13',
    redirectUrl: 'https://www.magicbricks.com/'
  },
  {
    id: 'r7_2',
    title: 'GGSIPU Dwarka Sector 14 Metro Side PG & Rooms',
    type: 'pg',
    rent: 8500,
    city: 'Delhi',
    distanceFromCampus: 0.5,
    amenities: ['WiFi', 'AC', 'Mess Food', 'Metro Walk'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Dwarka IP Stays',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c7',
    redirectUrl: 'https://www.housing.com/rent/pg-in-delhi'
  },
  {
    id: 'r14',
    title: 'Oriental University Student House Indore',
    type: 'sharing',
    rent: 5200,
    city: 'Indore',
    distanceFromCampus: 1.5,
    amenities: ['WiFi', 'Study Room', 'Canteen'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Indore Central Stays',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c14',
    redirectUrl: 'https://www.housing.com/rent/pg-in-indore'
  },
  {
    id: 'r15',
    title: 'Student Single Room near DAVV Indore',
    type: 'single',
    rent: 6000,
    city: 'Indore',
    distanceFromCampus: 1.1,
    amenities: ['WiFi', 'AC', 'Attached Bath'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Indore Student PG',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c15',
    redirectUrl: 'https://www.stanzaliving.com/indore'
  },
  {
    id: 'r16',
    title: 'Amity Noida Sector 125 Luxury Boys & Girls PG',
    type: 'pg',
    rent: 11500,
    city: 'Noida',
    distanceFromCampus: 0.5,
    amenities: ['WiFi', 'AC', 'Food Included', 'Gym', 'Laundry'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Amity Student Care',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c16',
    redirectUrl: 'https://www.stanzaliving.com/noida'
  },
  {
    id: 'r17',
    title: 'Spacious Girls Hostel near Sharda University',
    type: 'hostel',
    rent: 8000,
    city: 'Greater Noida',
    distanceFromCampus: 0.4,
    amenities: ['WiFi', 'AC', 'Food', 'Gym', 'Laundry'],
    genderPreference: 'female',
    status: 'available',
    verified: true,
    ownerName: 'Sharda Girls Residency',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c17',
    redirectUrl: 'https://www.magicbricks.com/'
  },
  {
    id: 'r18',
    title: 'SRM Kattankulathur Chennai Premium PG',
    type: 'pg',
    rent: 9500,
    city: 'Chennai',
    distanceFromCampus: 1.0,
    amenities: ['WiFi', 'AC', 'South & North Food', 'Laundry'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'SRM Student Housing',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c18',
    redirectUrl: 'https://www.stanzaliving.com/chennai'
  },
  {
    id: 'r19',
    title: 'Premium PG for VIT Vellore Students',
    type: 'pg',
    rent: 9000,
    city: 'Vellore',
    distanceFromCampus: 0.9,
    amenities: ['WiFi', 'Food', 'AC', 'Study Room'],
    genderPreference: 'male',
    status: 'available',
    verified: true,
    ownerName: 'Vellore Residency',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c19',
    redirectUrl: 'https://www.housing.com/rent/pg-in-vellore'
  },
  {
    id: 'r20',
    title: 'Manipal Student Apartment & Twin Room',
    type: 'sharing',
    rent: 8500,
    city: 'Manipal',
    distanceFromCampus: 1.2,
    amenities: ['WiFi', 'AC', 'Kitchen', 'Balcony'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Manipal Living',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c20',
    redirectUrl: 'https://www.amberstudent.com/'
  },
  {
    id: 'r21',
    title: 'Thapar Patiala Campus Side Deluxe Room',
    type: 'single',
    rent: 6800,
    city: 'Patiala',
    distanceFromCampus: 0.7,
    amenities: ['WiFi', 'Power Backup', 'Study Table'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Patiala PG Hub',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c21',
    redirectUrl: 'https://www.housing.com/'
  },
  {
    id: 'r22',
    title: 'KIIT Bhubaneswar Student Residence & Mess',
    type: 'pg',
    rent: 7200,
    city: 'Bhubaneswar',
    distanceFromCampus: 0.8,
    amenities: ['WiFi', 'AC', 'Food', 'Laundry'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'KIIT Care Stays',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c22',
    redirectUrl: 'https://www.magicbricks.com/'
  },
  {
    id: 'r23',
    title: 'Symbiosis Student Flat-Share Pune',
    type: 'sharing',
    rent: 11000,
    city: 'Pune',
    distanceFromCampus: 1.2,
    amenities: ['WiFi', 'Kitchen', 'Washing Machine', 'Balcony'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Kulkarni Flats',
    imageUrls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c23',
    redirectUrl: 'https://www.stanzaliving.com/pune'
  },
  {
    id: 'r24',
    title: 'Chandigarh University Mohali Student PG',
    type: 'pg',
    rent: 6500,
    city: 'Mohali',
    distanceFromCampus: 1.4,
    amenities: ['WiFi', 'Food', 'Power Backup', 'Geyser'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Mohali Student Hub',
    imageUrls: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c24',
    redirectUrl: 'https://www.housing.com/rent/pg-in-chandigarh'
  },
  {
    id: 'r25',
    title: 'SRM Sonepat Student Residency',
    type: 'single',
    rent: 6200,
    city: 'Sonepat',
    distanceFromCampus: 1.0,
    amenities: ['WiFi', 'Mess', 'Library Desk'],
    genderPreference: 'any',
    status: 'available',
    verified: true,
    ownerName: 'Sonepat Care',
    imageUrls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
    collegeId: 'c25',
    redirectUrl: 'https://www.nobroker.in/'
  }
];

export const MOCK_ROOMMATES: RoommateProfile[] = [
  {
    id: 'rm1',
    name: 'Karan Singh',
    collegeId: 'c1',
    departmentId: 'cs1',
    department: 'B.Tech Computer Science',
    budget: 10000,
    lifestyle: { sleep: 'night_owl', smoking: 'non_smoker', food: 'any', cleanliness: 'neat' },
    compatibility: 92,
    bio: 'Coding till 3 AM. Looking for a chill flatmate who keeps common areas clean.'
  },
  {
    id: 'rm2',
    name: 'Sneha Patel',
    collegeId: 'c2',
    departmentId: 'bcom1',
    department: 'B.Com (Hons)',
    budget: 15000,
    lifestyle: { sleep: 'early', smoking: 'non_smoker', food: 'veg', cleanliness: 'neat' },
    compatibility: 85,
    bio: 'Early riser, focused on studies. Need a quiet place.'
  },
  {
    id: 'rm3',
    name: 'Rohan Desai',
    collegeId: 'c1',
    departmentId: 'bca1',
    department: 'BCA',
    budget: 8000,
    lifestyle: { sleep: 'night_owl', smoking: 'smoker', food: 'non_veg', cleanliness: 'relaxed' },
    compatibility: 45,
    bio: 'Easy going, love music and gaming.'
  }
];

export const MOCK_SENIORS: SeniorProfile[] = [
  {
    id: 's1',
    name: 'Anjali Sharma',
    collegeId: 'c1',
    departmentId: 'cs1',
    department: 'B.Tech CSE',
    graduationYear: 2022,
    company: 'Google',
    role: 'Software Engineer',
    verified: true,
    mentorshipAvailable: true
  },
  {
    id: 's2',
    name: 'Vikram Gupta',
    collegeId: 'c2',
    departmentId: 'bca1',
    department: 'BCA',
    graduationYear: 2021,
    company: 'Deloitte',
    role: 'Analyst',
    verified: true,
    mentorshipAvailable: false
  },
  {
    id: 's3',
    name: 'Megha Reddy',
    collegeId: 'c3',
    departmentId: 'cs2',
    department: 'B.Tech ECE',
    graduationYear: 2023,
    company: 'Microsoft',
    role: 'Product Manager',
    verified: true,
    mentorshipAvailable: true
  }
];

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: 'i1',
    title: 'Frontend Developer Intern',
    company: 'Zomato',
    location: 'Gurgaon (Hybrid)',
    type: 'internship',
    stipend: '₹30,000/mo',
    tags: ['React', 'TypeScript', 'Web'],
    postedAt: '2 days ago',
    collegeId: 'c1'
  },
  {
    id: 'i2',
    title: 'Product Design Intern',
    company: 'Cred',
    location: 'Bangalore (On-site)',
    type: 'internship',
    stipend: '₹40,000/mo',
    tags: ['Figma', 'UI/UX'],
    postedAt: '5 days ago'
  },
  {
    id: 'i3',
    title: 'SDE-1',
    company: 'Amazon',
    location: 'Remote',
    type: 'full_time',
    stipend: 'Competitive',
    tags: ['Java', 'AWS', 'Backend'],
    postedAt: '1 week ago'
  }
];
